### ISSUE TITLE
Documentation or example code

### ISSUE THREAD

**Issue by huggre** [HerrHofrat/deconz_py#3]
Hi, do you have some documentation or example code for this library.
I'm looking to do some basic interaction with deConz (turning lights on/off) from a Python script and was hoping i did not have to write a wrapper for the deConz REST API myself

**Comment by HerrHofrat** [comment]
Hi! I wrote this library for my custom deconz home assistant integration - but due to lack of time I discontinued with that integration and switched to the official one, which also means I discontinued development of the deconz_py library. I'd recommend you to use https://github.com/Kane610/deconz instead of my library
